version: "3"
services:

  grpc:
    build:
      context: .
      dockerfile: Dockerfile-gRPC
    ports:
      - "50051"
    container_name: grpc_server
    deploy:
      restart_policy:
        condition: on-failure

  rest:
    build:
      context: .
      dockerfile: Dockerfile-rest
    ports:
      - "8000"
    container_name: rest_server
    deploy:
      restart_policy:
        condition: on-failure

