# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CustomerInfoSvc_pb2 as CustomerInfoSvc__pb2


class CustomerInfoSvcStub(object):
  """CustomerInfoSvc holds actual service definition which would give back actual information.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCustomerInformation = channel.unary_unary(
        '/CustomerInfoSvc.CustomerInfoSvc/getCustomerInformation',
        request_serializer=CustomerInfoSvc__pb2.CustomerInfoSvcRequest.SerializeToString,
        response_deserializer=CustomerInfoSvc__pb2.CustomerInfoSvcResponse.FromString,
        )


class CustomerInfoSvcServicer(object):
  """CustomerInfoSvc holds actual service definition which would give back actual information.
  """

  def getCustomerInformation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CustomerInfoSvcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCustomerInformation': grpc.unary_unary_rpc_method_handler(
          servicer.getCustomerInformation,
          request_deserializer=CustomerInfoSvc__pb2.CustomerInfoSvcRequest.FromString,
          response_serializer=CustomerInfoSvc__pb2.CustomerInfoSvcResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CustomerInfoSvc.CustomerInfoSvc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
