# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomerInfoSvc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Customer_pb2 as Customer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CustomerInfoSvc.proto',
  package='CustomerInfoSvc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x43ustomerInfoSvc.proto\x12\x0f\x43ustomerInfoSvc\x1a\x0e\x43ustomer.proto\",\n\x16\x43ustomerInfoSvcRequest\x12\x12\n\ncustomerId\x18\x01 \x01(\x03\"F\n\x17\x43ustomerInfoSvcResponse\x12+\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x19.CustomerInfoSvc.Customer2\x80\x01\n\x0f\x43ustomerInfoSvc\x12m\n\x16getCustomerInformation\x12\'.CustomerInfoSvc.CustomerInfoSvcRequest\x1a(.CustomerInfoSvc.CustomerInfoSvcResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[Customer__pb2.DESCRIPTOR,])




_CUSTOMERINFOSVCREQUEST = _descriptor.Descriptor(
  name='CustomerInfoSvcRequest',
  full_name='CustomerInfoSvc.CustomerInfoSvcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customerId', full_name='CustomerInfoSvc.CustomerInfoSvcRequest.customerId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=102,
)


_CUSTOMERINFOSVCRESPONSE = _descriptor.Descriptor(
  name='CustomerInfoSvcResponse',
  full_name='CustomerInfoSvc.CustomerInfoSvcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='CustomerInfoSvc.CustomerInfoSvcResponse.customer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=174,
)

_CUSTOMERINFOSVCRESPONSE.fields_by_name['customer'].message_type = Customer__pb2._CUSTOMER
DESCRIPTOR.message_types_by_name['CustomerInfoSvcRequest'] = _CUSTOMERINFOSVCREQUEST
DESCRIPTOR.message_types_by_name['CustomerInfoSvcResponse'] = _CUSTOMERINFOSVCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomerInfoSvcRequest = _reflection.GeneratedProtocolMessageType('CustomerInfoSvcRequest', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERINFOSVCREQUEST,
  __module__ = 'CustomerInfoSvc_pb2'
  # @@protoc_insertion_point(class_scope:CustomerInfoSvc.CustomerInfoSvcRequest)
  ))
_sym_db.RegisterMessage(CustomerInfoSvcRequest)

CustomerInfoSvcResponse = _reflection.GeneratedProtocolMessageType('CustomerInfoSvcResponse', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERINFOSVCRESPONSE,
  __module__ = 'CustomerInfoSvc_pb2'
  # @@protoc_insertion_point(class_scope:CustomerInfoSvc.CustomerInfoSvcResponse)
  ))
_sym_db.RegisterMessage(CustomerInfoSvcResponse)



_CUSTOMERINFOSVC = _descriptor.ServiceDescriptor(
  name='CustomerInfoSvc',
  full_name='CustomerInfoSvc.CustomerInfoSvc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=177,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='getCustomerInformation',
    full_name='CustomerInfoSvc.CustomerInfoSvc.getCustomerInformation',
    index=0,
    containing_service=None,
    input_type=_CUSTOMERINFOSVCREQUEST,
    output_type=_CUSTOMERINFOSVCRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CUSTOMERINFOSVC)

DESCRIPTOR.services_by_name['CustomerInfoSvc'] = _CUSTOMERINFOSVC

# @@protoc_insertion_point(module_scope)
